services:
  springboot-app:
    #container_name: spring-app
    build: .
    image: springboot2-app
    restart: always
    ports:
      - "8484:8080"
 # zookeeper:
   # image: confluentinc/cp-zookeeper:latest
    #environment:
     # ZOOKEEPER_CLIENT_PORT: 2181
      #ZOOKEEPER_TICK_TIME: 2000
  #kafka:
   # image: confluentinc/cp-kafka:latest
    #depends_on:
    #  - zookeeper
    #ports:
    #  - "9092:9092"
    #environment:
     # KAFKA_BROKER_ID: 1
    #  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
   #   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
   # environment:
      #MYSQL_HOST: mysqldb_spring
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
     # MYSQL_PORT: 3306
   # depends_on:
    #  - mysqldb_spring
  #mysqldb_spring:
    #container_name: mysqldb_spring
    #image: mysql
    #ports:
     # - 3308:3306
   # environment:
     # MYSQL_DATABASE: spring_web_blog
     # MYSQL_ROOT_PASSWORD: root